### ISSUE TITLE
Error: This flash tool just support Ubuntu now

### ISSUE THREAD

**Issue by vagrale13** [khadas/utils#12]
I have the following error when i try to install 

```
$ sudo ./INSTALL
[sudo] password for : 

===============================================

Host PC: LinuxMint 18.3

===============================================

Error: This flash tool just support Ubuntu now, other distributions haven't been verified!
```

**Comment by numbqq** [comment]
> Host PC: LinuxMint 18.3

We haven't checked on LinuxMint yet. You can comment the check script to have a try.

**Comment by vagrale13** [comment]
Ok, finally i install it, but didn't detect in 
`$ lsusb | grep Amlogic`

**Comment by vagrale13** [comment]
Tested today with **LinuxMint 20.1** and works perfectly.
The only that i did, is to comment lines _30,31,32,33_ from **INSTALL** file, 
and i did copy the file _70-persistent-usb-ubuntu12.rules_ manually to /etc/udev/rules.d
Also, _aml-burn-tool_ command worked only with _sudo_

**Comment by numbqq** [comment]
> Also, aml-burn-tool command worked only with sudo

You need to reboot or logout the system.

**Comment by vagrale13** [comment]
> > Also, aml-burn-tool command worked only with sudo
> 
> You need to reboot or logout the system.

You are right. After that doesn't need root permissions.
