### ISSUE TITLE
Installation on Ubuntu 18.10

### ISSUE THREAD

**Issue by pablitok** [khadas/utils#4]
To install on ubuntu 18.10, I had to modify INSTALL script:
on line 23 (local hostdeps="....) I changed lib32ncurses5 for libncurses5 and added ccache

**Comment by numbqq** [comment]
Hello @pablitok,

Seems `lib32ncurses5` doesn't exist in 18.10.

After your modifications, does it works? Can you burn image on 18.10?

**Comment by pablitok** [comment]
Yeah, it works! Thanks

**Comment by numbqq** [comment]
OK. I will add this for ubuntu 18.10.

**Comment by numbqq** [comment]
fixed https://github.com/khadas/utils/commit/33c63bd10cc63f16ee4a35492c2fabc504b4338f
